services:
  gestion-juniors:
    build: .
    container_name: gestion-juniors
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - gestion-ejecutivos-net

networks:
  gestion-ejecutivos-net:
    external: true
